### PR TITLE
Keep cache in own directory

### PR DESCRIPTION
**Pull request by RiKap**
@ondrs It keeps the cache directory cleaner

If it is ok for you, please release new version.

### CODE REVIEW

**Comment by RiKap** [comment]
@ondrs Ok, but only like this. Otherwise it has this `_ondrs%5CHi%5CHi` weird directory name.

**Comment by ondrs** [comment]
@RiKap thank you!

**Comment by RiKap** [comment]
@ondrs Nice. Please can you release new version?

**Comment by ondrs** [comment]
@RiKap released v0.3.0

**Pull request merged**
